### ISSUE TITLE
Define the 7 outputs from get_optim() in documentation

### ISSUE THREAD

**Issue by TheTams** [rsh249/cRacle#4]
Currently the titles of the lists in the output from get_optim() do not make it clear to the user, which output corresponds which method as discussed in Harbert and Baryiames 2019. I have been unable to find any documentation that defines them elsewhere. The categories are:
conintkde
conintgauss
origk
origg
dircontint
means
sds

**Comment by rsh249** [comment]
I will work on this documentation as well. These names are a holdover from how I initially set up the models and output collection, but we worked on the terms in the last publication a bit more to better align with the modeling that was actually taking place.

For a quick reference: 

- The "*kde" and "*k" methods are non-parametric models described in the Harbert & Baryiames, 2019 paper. 
- The "*gauss"  and "*g" methods are the parametric models.
- "conint" returns 95% confidence intervals of both methods
- "orig" returns an estimate of the maximum likelihood value (the exact values aren't calculated but a narrow interval around the maximum is easy to get.
- dirconint is functionally equivalent to conintgauss but uses the weighted means method instead of the ML method.
- means is equivalent to origg but uses the weighted means method instead of the ML method.
- sds is a calculation to go with means of the weighted standard deviation (something you don't get with the ML method but I haven't looked into much).

I hope this helps for now.

**Comment by TheTams** [comment]
Thank you for that, I thought I had figured some of it out... 
So is the weighted means the equivalent of the MCRM from Thompson et al. (2012)? And none of these are equivalent to the Coexistence Approach?

**Comment by rsh249** [comment]
The weighted means is equivalent to the parametric CRACLE. There is a separate function for MCR  a la Thompson et al. 2012 that does the unweighted MCR which (I think) is the same as the coexistence approach.

**Comment by TheTams** [comment]
Sorry, my bad, I see the MCR one there. Thanks, that's great.

**Comment by rsh249** [comment]
Resolved in documentation in the latest commit: https://github.com/rsh249/cRacle/commit/3fecc7331c4d98d8914275d0209d20648e67fcbe
